let temp=null
// console.log(typeof temp)
// console.log("2"==2)
// console.log("1"+2+2)
// console.log(1+"2"+"2")
// console.log(1+2+"2")
let isavailable=Boolean(temp)
console.log(isavailable)
let tempval=Number(temp)
console.log(tempval)
console.log(2>"1")
console.log("2">"1")
console.log("aachin">"aditya")